openapi: 3.0.1
info:
  title: Trending Music Plugin
  description: |
    A plugin that allows the user to get top songs search for using Shazam. It provides global top songs, top songs by country, top songs by genre, and top songs by country and genre.
    
    To use this plugin, you can make requests the following:
    - Get the top songs globally.
    - Get the top songs for a specific genre.'.
    - Get the top songs for a specific country.'.
    - Get the top songs for a specific country and genre.'.
    
    
  version: 'v1'
servers:
  - url: https://rising-analogy-387407.uc.r.appspot.com
paths:
  /top_songs:
    get:
      operationId: topSongs
      summary: Get the top songs globally
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /top_songs/{country}:
    get:
      operationId: topSongsCountry
      summary: Get the top songs for a specific country
      parameters:
        - in: path
          name: country
          schema:
            type: string
          required: true
          description: The country for which to get the top songs. Use the country's ISO 3166-1 alpha-2 code. For example, for the United States, use 'US'.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /top_songs/{country}/{genre}:
    get:
      operationId: topSongsCountryGenre
      summary: Get the top songs for a specific country and genre
      parameters:
        - in: path
          name: country
          schema:
            type: string
          required: true
          description: The country for which to get the top songs. Use the country's ISO 3166-1 alpha-2 code. For example, for the United States, use 'US'.
        - in: path
          name: genre
          schema:
            type: string
          required: true
          description: |
            The genre for which to get the top songs. Use the genre's specific code. For example, for Hip Hop, use 'HIP_HOP_RAP'.
            
            Available genres: POP, HIP_HOP_RAP, DANCE, ELECTRONIC, RNB_SOUL, ALTERNATIVE, ROCK, LATIN, FILM_TV_STAGE, COUNTRY, AFRO_BEATS, WORLDWIDE, REGGAE_DANCE_HALL, HOUSE, K_POP, FRENCH_POP, SINGER_SONGWRITER, REGIONAL_MEXICANO.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /top_songs/genre/{genre}:
    get:
      operationId: topSongsGenre
      summary: Get the top songs for a specific genre
      parameters:
        - in: path
          name: genre
          schema:
            type: string
          required: true
          description: |
            The genre for which to get the top songs. Use the genre's specific code. For example, for Hip Hop, use 'HIP_HOP_RAP'.
            
            Available genres: POP, HIP_HOP_RAP, DANCE, ELECTRONIC, RNB_SOUL, ALTERNATIVE, ROCK, LATIN, FILM_TV_STAGE, COUNTRY, AFRO_BEATS, WORLDWIDE, REGGAE_DANCE_HALL, HOUSE, K_POP, FRENCH_POP, SINGER_SONGWRITER, REGIONAL_MEXICANO.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
  /.well-known/ai-plugin.json:
    get:
      operationId: manifest
      summary: Get the AI plugin manifest
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
